apiVersion: batch/v1
kind: CronJob
metadata:
  name: ecr-vulnerability-scan
  namespace: default
spec:
  # Run scans at 10:00AM UTC on weekdays
  # TODO: Include CRON_TZ=UTC when on K8s 1.22+
  # schedule: "CRON_TZ=UTC 0 10 * * 1-5"
  # Run scans at 10:00AM (in kube-controller-manager's timezone) on weekdays
  schedule: "0 10 * * 1-5"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: k8s-ecr-runtime-scanner
        spec:
          containers:
            - args:
                - --namespaces=$(NAMESPACE)
                - --include-non-ecr-images
              env:
                - name: AWS_DEFAULT_REGION
                  value: us-east-1
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              name: kube-ecr-image-scanner
              image: public.ecr.aws/t5o6f0a6/kube-ecr-image-scanner:latest
              imagePullPolicy: Always
              resources:
                requests:
                  memory: 8Gi
                limits:
                  memory: 8Gi
              volumeMounts:
                - name: tmp
                  mountPath: /tmp
              securityContext:
                readOnlyRootFilesystem: true
          serviceAccountName: kube-ecr-image-scanner
          restartPolicy: OnFailure
          volumes:
            - emptyDir:
                medium: Memory
              name: tmp
