apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: kube-ecr-image-scanner

namespace: default

resources:
  - cronjob.yaml
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
