apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kube-ecr-image-scanner
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
      - get
