apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-ecr-image-scanner
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-ecr-image-scanner
subjects:
  - kind: ServiceAccount
    name: kube-ecr-image-scanner
    namespace: default
