apiVersion: batch/v1
kind: CronJob
metadata:
  name: ecr-vulnerability-scan
spec:
  schedule: "@daily"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - args:
                - --scan-namespaces=dev,staging,production
                - --include-non-ecr-images
              name: kube-ecr-image-scanner
              image: 146771500595.dkr.ecr.us-east-1.amazonaws.com/kube-ecr-image-scanner:latest
              imagePullPolicy: Always
          restartPolicy: OnFailure
